config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
    validates :name, uniqueness: true, presence: true
    validates :address, presence: true
    validates :description, uniqueness: true, presence: true
    validates :number_of_guests, inclusion: { in: [1,2,3,4,5,6,7,8,9,10,11], allow_nil: false}
end

# validates :name, exclusion: { in: %w(admin administrator owner) }

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    before_action :set_flat, only: [:show, :edit, :update, :destroy]

    # GET /flats
    # GET /flats.json
    def index
        # search bar
        if params[:query].present?
          @query = params[:query]
          @flats = Flat.where("name LIKE ?", "%#{@query}%")
          # @flats = Flat.where("name ilike ?", '%#{params[:query]}%')
        else
          @flats = Flat.all
        end
    end
  
    # GET /flats/1
    # GET /flats/1.json
    def show
    end
  
    # GET /flats/new
    def new
      @flat = Flat.new
    end
  
    # GET /flats/1/edit
    def edit
    end
  
    # POST /flats
    # POST /flats.json
    def create
      @flat = Flat.new(flat_params)
  
      respond_to do |format|
        if @flat.save
          format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
          format.json { render :show, status: :created, location: @flat }
        else
          format.html { render :new }
          format.json { render json: @flat.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /flats/1
    # PATCH/PUT /flats/1.json
    def update
      respond_to do |format|
        if @flat.update(flat_params)
          format.html { redirect_to @flat, notice: 'flat was successfully updated.' }
          format.json { render :show, status: :ok, location: @flat }
        else
          format.html { render :edit }
          format.json { render json: @flat.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /flats/1
    # DELETE /flats/1.json
    def destroy
      @flat.destroy
      respond_to do |format|
        format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_flat
        @flat = Flat.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def flat_params
        params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |f| %>
  <% if flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
        <% flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_guests %>
    <%= f.number_field :number_of_guests, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price_per_night %>
    <%= f.number_field :price_per_night, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', flats_path, class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit flat</h1>
        <div class="mt-3">
            <%= render 'form', flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
      <% else %>
        <p>All <%= Flat.count %> flats.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>')"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <i class="fa fa-user-plus" aria-hidden="true">&nbsp;</i><span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex ml-3">
                <i class="material-icons mr-2">€</i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'ml-3 text-warning' %>
            <%= link_to "Remove", flat_path(flat),
                method: :delete, 
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>New flat</h1>
        <div class="mt-3">
            <%= render 'form', flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('<%= @flat.picture_url %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @flat.address %>&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C<%= @flat.address %>&key=AIzaSyDAYd819ySkp7bz1-oDhaP1EZDCScffB1Y')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="fa fa-user-plus" aria-hidden="true">&nbsp;</i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">€</i> <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook fa-2x mr-2" aria-hidden="true"></i>
            <i class="fa fa-twitter fa-2x mr-2"></i>
            <i class="fa fa-pinterest fa-2x mr-2"></i>
            <i class="fa fa-envelope fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/da5314af74.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%#= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%#= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/flats">Simple Airbnb</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
        </div>
      </div>
</nav>